### ISSUE TITLE
虚拟目录似乎还是不行

### ISSUE THREAD

**Issue by maikebing** [UlyssesWu/UniFTP#2]

**Comment by UlyssesWu** [comment]
When I made this project, it was required to make such wheels. 

Feel free to import (by yourself) any real-life virtual file systems such as https://github.com/platformdotnet/Platform.VirtualFileSystem or https://github.com/bobvanderlinden/sharpfilesystem . 

提issue只写标题，不详细说明，没有人能理解你说的是什么。

**Comment by maikebing** [comment]
UniFTP的 AddLink 我测试好多遍， 都不能实现

**Comment by maikebing** [comment]
都不能实现ftp的 虚拟目录功能。

**Comment by UlyssesWu** [comment]
"It Works on My Machine".

Please make a simple debug if you consider yourself a programmer.

Hint:

You need `VDirectory.Refresh()` after `AddLink` to make it actually works. For details, check https://github.com/UlyssesWu/UniFTP/blob/0a1e75c1b6363fa1cd624202b659b8a25a52042c/UniFTP.Server/Virtual/VirtualFileSystem.cs#L63-L67 
We didn't do refresh automatically, just for performance consideration.
