### ISSUE TITLE
Maybe a BUG, after receiving some files, becomes slow and eventually stops receiving files.

### ISSUE THREAD

**Issue by maikebing** [UlyssesWu/UniFTP#3]
Maybe a BUG, after receiving some files, becomes slow and eventually stops receiving files.  But the restart was normal again.

**Comment by UlyssesWu** [comment]
Maybe, but I have no idea how to reproduce this bug... I tried uploading many files but it still works as normal. 

If there is no specific repro steps, maybe you have to debug by yourself.

(I'm using the .NET Framework build, with the WinForm GUI.)

建议你用VS Debug模式运行，看下传输多个文件后是否有内存泄露等情况。
